# Generated by Django 4.2.11 on 2024-03-18 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('inspection', "Texnik ko'rikda"), ('petrol_station', 'AYOQSHda'), ('ready', 'Amaliyotga tayyor'), ('in_progress', 'Bajarilmoqda'), ('successful', 'Muvaffaqiyatli bajarildi'), ('canceled', 'Bekor qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=50)),
                ('automobile_type', models.CharField(choices=[('armored', 'Zirxli texnika'), ('unarmored', 'Zirxsiz texnika')], default='unarmored', max_length=50, verbose_name='Texnika turi')),
                ('date_time', models.DateTimeField()),
                ('route', models.CharField(max_length=50, verbose_name="Yo'nalish")),
                ('passengers_count', models.IntegerField(blank=True, null=True, verbose_name="Yo'lovchilar soni")),
                ('file', models.FileField(blank=True, null=True, upload_to='applications/', verbose_name='Bildirgi fayli')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Ariza beruvchi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Ariza',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': "Yoqilg'i turi",
                'verbose_name_plural': "Yoqilg'i turilari",
            },
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255, verbose_name='Raqami')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('short_name', models.CharField(max_length=255, verbose_name='Qisqa nomi')),
            ],
            options={
                'verbose_name': 'Harbiy qism',
                'verbose_name_plural': 'Harbiy qism',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Raqami')),
                ('tex_passport', models.CharField(max_length=100, unique=True, verbose_name='Tex. passport')),
                ('model', models.CharField(max_length=255, verbose_name='Modeli')),
                ('color', models.CharField(max_length=100, verbose_name='Rangi')),
                ('year', models.IntegerField(verbose_name='Ishlab chiqarilgan yili')),
                ('automobile_type', models.CharField(choices=[('armored', 'Zirxli texnika'), ('unarmored', 'Zirxsiz texnika')], max_length=50, verbose_name='Texnika turi')),
                ('odometr', models.IntegerField(verbose_name='Odometr')),
                ('fuel_consumption', models.IntegerField(verbose_name="Yoqilg'i sarfi(100 km, litr)")),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Haydovchi')),
                ('fuel_type', models.ManyToManyField(to='main.fueltype', verbose_name="Yoqilg'i turi")),
            ],
            options={
                'verbose_name': 'Texnika',
                'verbose_name_plural': 'Texnikalar',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valume', models.IntegerField(default=0, verbose_name='Hajmi')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Ariza')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fueltype', verbose_name="Yoqilg'i turi")),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicles', verbose_name='Texnika')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unsatisfactory', 'Qoniqarsiz'), ('satisfactory', 'Qoniqarli'), ('good', 'Yaxshi'), ('excellent', "A'lo")], max_length=50)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Ariza')),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicles', verbose_name='Texnika')),
            ],
            options={
                'verbose_name': "Texnik ko'rik",
                'verbose_name_plural': "Texnik ko'rik",
            },
        ),
        migrations.AddField(
            model_name='application',
            name='military_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.militaryunit'),
        ),
        migrations.AddField(
            model_name='application',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='main.vehicles', verbose_name='Moshina'),
        ),
    ]
