# Generated by Django 4.2.11 on 2024-03-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_fuels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yoq_nomi', models.TextField(max_length=255)),
                ('art', models.IntegerField()),
                ('bmp', models.IntegerField()),
                ('avto', models.IntegerField()),
                ('uchuv', models.IntegerField()),
                ('tank', models.IntegerField()),
                ('trak', models.IntegerField()),
                ('maxs', models.IntegerField()),
                ('ishab', models.IntegerField()),
                ('rim1', models.IntegerField()),
                ('rim2', models.IntegerField()),
                ('rim3', models.IntegerField()),
                ('rim4', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
