# Generated by Django 4.2.11 on 2024-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_add_fuels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_fuels',
            name='art',
            field=models.IntegerField(verbose_name='ARt tiyagachi '),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='avto',
            field=models.IntegerField(verbose_name='Avtomobillar'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='bmp',
            field=models.IntegerField(verbose_name='BMP, BTR, mototsikillar '),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='ishab',
            field=models.IntegerField(verbose_name=' Ishlab chiqarish va texnik extiyojlar'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='maxs',
            field=models.IntegerField(verbose_name='Maxsus mashinalarning avtonom divigatellari statsionar divigatellar '),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='rim1',
            field=models.IntegerField(verbose_name=' I'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='rim2',
            field=models.IntegerField(verbose_name='II'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='rim3',
            field=models.IntegerField(verbose_name='III'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='rim4',
            field=models.IntegerField(verbose_name='IV'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='tank',
            field=models.IntegerField(verbose_name='Tanklar SAU'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='trak',
            field=models.IntegerField(verbose_name='Traktor va muxandislik texnikalari va qurilish mexanizmlar'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='uchuv',
            field=models.IntegerField(verbose_name=' Uchuvchi aparatlar'),
        ),
        migrations.AlterField(
            model_name='add_fuels',
            name='yoq_nomi',
            field=models.TextField(max_length=255, verbose_name="Yoqilg'i nomi"),
        ),
    ]
