# Generated by Django 4.2.11 on 2024-03-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('short_title', models.CharField(max_length=255, verbose_name='Qisqartma')),
            ],
            options={
                'verbose_name': 'Harbiy unvonlar',
                'verbose_name_plural': 'Harbiy unvonlar',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='military_rank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='authentication.militaryrank', verbose_name='Harbiy unvon'),
            preserve_default=False,
        ),
    ]
