# Generated by Django 4.2.11 on 2024-03-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_militaryrank_customuser_military_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='military_rank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.militaryrank', verbose_name='Harbiy unvon'),
        ),
    ]
