# Generated by Django 4.2.11 on 2024-03-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_military_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Haydovchimi'),
        ),
    ]
